name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Post build results to Slack
        if: failure()
        run: |
            STATUS=$([[ "${{ job.status }}" == "success" ]] && echo "passed" || echo "failed")
            curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" \
            -H 'Content-type: application/json' \
            --data "{
              \"channel\": \"${{ secrets.SLACK_CHANNEL }}\",
              \"text\": \"Build *$STATUS*: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View results here>\"
            }" https://slack.com/api/chat.postMessage
